import test from 'node:test'
import assert from 'node:assert/strict'
import { _electron as electron } from 'playwright'
import { mkdir,mkdtemp } from 'node:fs/promises'
import { resolve } from 'node:path'
import { mainPage,panelPage } from './helpers.mjs'

test('agent selection synchronizes windows, persists, guards drafts and validates IPC',async()=>{
  await mkdir('test-results/profiles',{recursive:true})
  const profile=await mkdtemp(resolve('test-results/profiles/agents-'))
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;delete env.ELECTRON_RENDERER_URL
  const launch=()=>electron.launch({args:['.',`--user-data-dir=${profile}`],env})
  let app=await launch()
  try{
    const page=await mainPage(app)
    await page.evaluate(()=>window.localino.selectAgent('pi'))
    await page.locator('[data-agent="pi"]').waitFor()
    const panel=await panelPage(app)
    await page.evaluate(()=>window.localino.openPanel())
    const picker=panel.getByRole('button',{name:'Agent: Pi',exact:true})
    assert.equal(await picker.getAttribute('aria-expanded'),'false')
    assert.equal(await picker.locator('.agent-logo').evaluate(element=>getComputedStyle(element).borderRadius),'999px')
    await picker.click()
    assert.equal(await picker.getAttribute('aria-expanded'),'true')
    await panel.getByRole('menuitemradio',{name:'Claude Code',exact:true}).click()
    await page.locator('[data-agent="claude"]').waitFor()
    await page.evaluate(()=>window.localino.selectAgent('opencode'))
    await page.locator('[data-agent="opencode"]').waitFor()
    await panel.evaluate(()=>window.localino.openDashboard())
    await page.getByRole('button',{name:'Commands',exact:true}).click()
    assert.match(await page.locator('#command-usage').innerText(),/Connect a source first/)
    assert.equal(await page.locator('#command-quotas').getAttribute('aria-disabled'),'true')
    assert.match(await page.locator('#command-quotas').innerText(),/account quotas/)
    await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click()
    await app.evaluate(({Tray})=>{const original=Tray.prototype.setContextMenu;Tray.prototype.setContextMenu=function(menu){globalThis.agentMenu=menu;return original.call(this,menu)}})
    await page.evaluate(()=>window.localino.connectAgent('opencode'))
    await page.waitForFunction(()=>document.querySelector('[data-agent="opencode"] [role="status"]')?.textContent!=='Lettura in corso…')
    assert.deepEqual(await app.evaluate(()=>globalThis.agentMenu.items.filter(item=>item.type!=='separator').map(item=>item.label)),['Open Localino','Quit'])
    await page.evaluate(()=>window.localino.disconnectAgent('opencode'))
    await page.evaluate(()=>window.localino.selectAgent('pi'))
    await page.locator('[data-agent="pi"]').waitFor()
    assert.ok(Object.values((await page.evaluate(()=>window.localino.getAgents())).sources).every(source=>!source.enabled))
    for(const method of ['selectAgent','getHistory','refreshHistory','connectAgent','disconnectAgent'])await assert.rejects(page.evaluate(method=>window.localino[method]('../secret'),method))
    await assert.rejects(page.evaluate(()=>window.localino.setAgentPeriod('pi','invalid')))
    await page.evaluate(()=>window.localino.openPanel())
    await panel.getByRole('button',{name:'New note',exact:true}).click()
    await panel.getByRole('textbox',{name:'Note text'}).fill('Bozza da conservare')
    await page.evaluate(()=>window.localino.selectAgent('opencode'))
    assert.equal((await page.evaluate(()=>window.localino.getAgents())).selected,'opencode')
    assert.equal(await panel.getByRole('dialog').count(),0)
    assert.equal(await panel.getByRole('textbox',{name:'Note text'}).inputValue(),'Bozza da conservare')
    await panel.getByRole('button',{name:'Save',exact:true}).click()
    await page.evaluate(()=>window.localino.selectAgent('opencode'))
    await page.locator('[data-agent="opencode"]').waitFor()
    await app.close();app=await launch()
    const restored=await mainPage(app)
    assert.equal((await restored.evaluate(()=>window.localino.getAgents())).selected,'opencode')
    await restored.evaluate(()=>window.localino.navigate('usage'))
    await restored.locator('[data-agent="opencode"]').waitFor()
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=usage')).setSize(800,600))
    assert.equal(await restored.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  }finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{})}
})
